# Bus
MOD_BUS = OrderedDict{String, String}(  
                                        "id_bus"            => "INTEGER PRIMARY KEY", 
                                        "name"              => "VARCHAR(225) NOT NULL",
                                        "alias"             => "VARCHAR(225) NOT NULL",
                                        "active"            => "BOOLEAN NOT NULL", 
                                        "latitude"          => "REAL NOT NULL",
                                        "longitude"         => "REAL NOT NULL", 
                                        "id_area"           => "INTEGER REFERENCES Area (id_area)",
                                        )

# Demand
MOD_DEMAND = OrderedDict{String, String}(  
                                            "id_dem"            => "INTEGER PRIMARY KEY", 
                                            "name"              => "VARCHAR(225) NOT NULL",
                                            "load_"             => "REAL NOT NULL",
                                            "id_bus"            => "INTEGER REFERENCES Bus (id_bus)",
                                            "active"            => "BOOLEAN NOT NULL",
                                            "controllable"      => "BOOLEAN NOT NULL",
                                            "voll"              => "REAL NOT NULL",
                                            "contingency"       => "BOOLEAN NOT NULL",
                                        )

# ESS
MOD_ESS                 = OrderedDict(  
                                        "id_ess"            => "INTEGER PRIMARY KEY", 
                                        "name"              => "VARCHAR(225) NOT NULL",
                                        "alias"             => "VARCHAR(225) NOT NULL",
                                        "tech"              => "VARCHAR(225) NOT NULL",
                                        "type"              => "VARCHAR(225) NOT NULL",
                                        "capacity"          => "REAL NOT NULL",
                                        "investment"        => "BOOLEAN NOT NULL",
                                        "active"            => "BOOLEAN NOT NULL",
                                        "id_bus"            => "INTEGER REFERENCES Bus (id_bus)", 
                                        "ch_eff"            => "REAL NOT NULL",
                                        "dch_eff"           => "REAL NOT NULL",
                                        "eini"              => "REAL NOT NULL",
                                        "emin"              => "REAL NOT NULL",
                                        "emax"              => "REAL NOT NULL",
                                        "pmin"              => "REAL NOT NULL",
                                        "pmax"              => "REAL NOT NULL",
                                        "lmin"              => "REAL NOT NULL",
                                        "lmax"              => "REAL NOT NULL",
                                        "fullout"           => "REAL NOT NULL",
                                        "partialout"        => "REAL NOT NULL",
                                        "mttrfull"          => "REAL NOT NULL",
                                        "mttrpart"          => "REAL NOT NULL",
                                        "inertia"           => "REAL NOT NULL",
                                        "powerfactor"       => "REAL NOT NULL",
                                        "ffr"               => "BOOLEAN NOT NULL",
                                        "pfr"               => "BOOLEAN NOT NULL",
                                        "res2"              => "BOOLEAN NOT NULL",
                                        "res3"              => "BOOLEAN NOT NULL",
                                        "fr_db"             => "REAL NOT NULL",
                                        "fr_ad"             => "REAL NOT NULL",
                                        "fr_dt"             => "REAL NOT NULL",
                                        "fr_frt"            => "REAL NOT NULL",
                                        "fr_fr"             => "REAL NOT NULL",
                                        "longitude"         => "REAL NOT NULL",
                                        "latitude"          => "REAL NOT NULL",
                                        "n"                 => "INTEGER NOT NULL", 
                                        "contingency"       => "BOOLEAN NOT NULL",
                                        )

# Generator 
MOD_GEN = OrderedDict{String, String}(  
                                        "id_gen"            => "INTEGER PRIMARY KEY", 
                                        "name"              => "VARCHAR(225) NOT NULL",
                                        "alias"             => "VARCHAR(225) NOT NULL",
                                        "fuel"              => "VARCHAR(225) NOT NULL",
                                        "tech"              => "VARCHAR(225) NOT NULL",
                                        "type"              => "VARCHAR(225) NOT NULL",
                                        "capacity"          => "REAL NOT NULL",
                                        "forate"            => "REAL NOT NULL",
                                        "fullout"           => "REAL NOT NULL",
                                        "partialout"        => "REAL NOT NULL",
                                        "derate"            => "REAL NOT NULL",
                                        "mttrfull"          => "REAL NOT NULL",
                                        "mttrpart"          => "REAL NOT NULL",
                                        "id_bus"            => "INTEGER REFERENCES Bus (id_bus)",
                                        "pmin"              => "REAL NOT NULL",
                                        "pmax"              => "REAL NOT NULL",
                                        "rup"               => "REAL NOT NULL",
                                        "rdw"               => "REAL NOT NULL",
                                        "investment"        => "BOOLEAN NOT NULL",
                                        "active"            => "BOOLEAN NOT NULL",
                                        "cvar"              => "REAL NOT NULL",
                                        "cfuel"             => "REAL NOT NULL",
                                        "cvom"              => "REAL NOT NULL",
                                        "cfom"              => "REAL NOT NULL",
                                        "co2"               => "REAL NOT NULL",
                                        "slope"             => "REAL NOT NULL",
                                        "hrate"             => "REAL NOT NULL",
                                        "pfrmax"            => "REAL NOT NULL",
                                        "g"                 => "REAL NOT NULL",
                                        "inertia"           => "REAL NOT NULL",
                                        "ffr"               => "BOOLEAN NOT NULL",
                                        "pfr"               => "BOOLEAN NOT NULL",
                                        "res2"              => "BOOLEAN NOT NULL",
                                        "res3"              => "BOOLEAN NOT NULL",
                                        "powerfactor"       => "REAL NOT NULL",
                                        "latitude"          => "REAL NOT NULL",
                                        "longitude"         => "REAL NOT NULL",
                                        "n"                 => "INTEGER NOT NULL",
                                        "contingency"       => "BOOLEAN NOT NULL",
                                        "down_time"         => "REAL NOT NULL",
                                        "up_time"           => "REAL NOT NULL",
                                        "last_state"        => "REAL NOT NULL",
                                        "last_state_period" => "REAL NOT NULL",
                                        "last_state_output" => "REAL NOT NULL",
                                        "start_up_cost"     => "REAL NOT NULL",
                                        "shut_down_cost"    => "REAL NOT NULL",
                                        "start_up_time"     => "REAL NOT NULL",
                                        "shut_down_time"    => "REAL NOT NULL",
                                        )
                                        
# Line
MOD_LINE = OrderedDict{String, String}(  
                                        "id_lin"            => "INTEGER PRIMARY KEY", 
                                        "name"              => "VARCHAR(225) NOT NULL",
                                        "alias"             => "VARCHAR(225) NOT NULL",
                                        "tech"              => "VARCHAR(225) NOT NULL",
                                        "capacity"          => "REAL NOT NULL",
                                        "id_bus_from"       => "INTEGER REFERENCES Bus (id_bus)",
                                        "id_bus_to"         => "INTEGER REFERENCES Bus (id_bus)",
                                        "investment"        => "BOOLEAN NOT NULL",
                                        "active"            => "BOOLEAN NOT NULL",
                                        "r"                 => "REAL NOT NULL",
                                        "x"                 => "REAL NOT NULL",
                                        "rvcap"             => "REAL NOT NULL",
                                        "fwcap"             => "REAL NOT NULL",
                                        "fullout"           => "REAL NOT NULL",
                                        "mttrfull"          => "REAL NOT NULL",
                                        "voltage"           => "REAL NOT NULL",
                                        "segments"          => "INTEGER NOT NULL",
                                        "latitude"          => "VARCHAR(225) NOT NULL",
                                        "longitude"         => "VARCHAR(225) NOT NULL",
                                        "length"            => "REAL NOT NULL",
                                        "n"                 => "INTEGER NOT NULL",
                                        "contingency"       => "BOOLEAN NOT NULL",
                                        )

MOD_DER = OrderedDict{String, String}(  "id_der"            => "INTEGER PRIMARY KEY", 
                                        "name"              => "VARCHAR(225) NOT NULL",
                                        "tech"              => "VARCHAR(225) NOT NULL",
                                        "id_dem"            => "INTEGER NOT NULL",
                                        "active"            => "BOOLEAN NOT NULL",
                                        "investment"        => "BOOLEAN NOT NULL",
                                        "capacity"          => "REAL NOT NULL",
                                        "reduct"            => "BOOLEAN NOT NULL",
                                        "pred_max"          => "REAL NOT NULL",
                                        "cost_red"          => "REAL NOT NULL",
                                        "n"                 => "INTEGER NOT NULL",
                                        )

TABLES_POWERSYSTEM = OrderedDict{String, OrderedDict{String, String}}(   
                                                    "Bus"                       => MOD_BUS,
                                                    "Demand"                    => MOD_DEMAND,
                                                    "ESS"                       => MOD_ESS,
                                                    "Generator"                 => MOD_GEN,
                                                    "Line"                      => MOD_LINE,
                                                    "DER"                       => MOD_DER,
                                    )