const ISP2026_FILE_TARGETS = ISPFileTarget[
    ISPFileTarget(:isp26_inputs,
                  "2026 ISP Inputs and Assumptions workbook",
                  "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/supporting-materials/2026-isp-inputs-and-assumptions-workbook.xlsm?rev=de6f5853cd5e4d5cbb06bc90bdf0e378&sc_lang=en";
                  filename = "2026-isp-inputs-and-assumptions-workbook.xlsm",
                  subdir = ""),
    ISPFileTarget(:isp26_outlook,
                  "2026 ISP generation and storage outlook",
                  "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/supporting-materials/2026-isp-generation-and-storage-outlook.zip?rev=b64eda28a46b4d3eb3e4b3cbafea3f84&sc_lang=en";
                  filename = "2026-isp-generation-and-storage-outlook.zip",
                  subdir = ""),
    ISPFileTarget(:isp26_model,
                  "2026 ISP Model",
                  "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/isp-model/2026-isp-model.zip?rev=78bfcf05ad414a8f9ba01f6a7c329fc2&sc_lang=en";
                  filename = "2026-isp-model.zip",
                  subdir = ""),
    ISPFileTarget(:isp26_solar_traces,
                  "2026 ISP Solar traces",
                  "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/isp-model/2026-isp-solar-traces.zip?rev=3ad06155b7b94628bc77b90efe94588e&sc_lang=en";
                  filename = "2026-isp-solar-traces.zip",
                  subdir = "zip/Traces"),
    ISPFileTarget(:isp26_wind_traces,
                  "2026 ISP Wind traces",
                  "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/isp-model/2026-isp-wind-traces.zip?rev=73674cd5bc6b4b7fbbc7d0e68ee0bc7c&sc_lang=en";
                  filename = "2026-isp-wind-traces.zip",
                  subdir = "zip/Traces"),
]

const ISP2026_SOURCE_METADATA = [
    (key = :isp26_inputs,
     title = "2026 ISP Inputs and Assumptions workbook",
     url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/supporting-materials/2026-isp-inputs-and-assumptions-workbook.xlsm?rev=de6f5853cd5e4d5cbb06bc90bdf0e378&sc_lang=en",
     filename = "2026-isp-inputs-and-assumptions-workbook.xlsm",
     status = :downloadable,
     local_path = "2026-isp-inputs-and-assumptions-workbook.xlsm",
     note = "Authoritative final 2026 ISP input workbook."),
    (key = :isp26_ev_support,
     title = "2025 IASR EV workbook referenced by the final 2026 ISP workbook",
     url = "https://aemo.com.au/-/media/files/stakeholder_consultation/consultations/nem-consultations/2024/2025-iasr-scenarios/final-docs/AEMO-2025-IASR-EV-workbook",
     filename = "aemo-2025-iasr-ev-workbook.xlsx",
     status = :required_local,
     local_path = "aemo-2025-iasr-ev-workbook.xlsx",
     note = "Required EV profile and charge-type support source referenced from the final 2026 ISP Inputs and Assumptions workbook."),
    (key = :isp26_outlook,
     title = "2026 ISP generation and storage outlook",
     url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/supporting-materials/2026-isp-generation-and-storage-outlook.zip?rev=b64eda28a46b4d3eb3e4b3cbafea3f84&sc_lang=en",
     filename = "2026-isp-generation-and-storage-outlook.zip",
     status = :downloadable,
     local_path = "2026-isp-generation-and-storage-outlook.zip",
     note = "Authoritative final 2026 ISP generation and storage outlook."),
    (key = :isp26_model,
     title = "2026 ISP Model",
     url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/isp-model/2026-isp-model.zip?rev=78bfcf05ad414a8f9ba01f6a7c329fc2&sc_lang=en",
     filename = "2026-isp-model.zip",
     status = :downloadable,
     local_path = "2026-isp-model.zip",
     note = "Authoritative final 2026 ISP model archive."),
    (key = :isp26_solar_traces,
     title = "2026 ISP Solar traces",
     url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/isp-model/2026-isp-solar-traces.zip?rev=3ad06155b7b94628bc77b90efe94588e&sc_lang=en",
     filename = "2026-isp-solar-traces.zip",
     status = :downloadable,
     local_path = "zip/Traces/2026-isp-solar-traces.zip",
     note = "Authoritative final 2026 ISP solar traces."),
    (key = :isp26_wind_traces,
     title = "2026 ISP Wind traces",
     url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/isp-model/2026-isp-wind-traces.zip?rev=73674cd5bc6b4b7fbbc7d0e68ee0bc7c&sc_lang=en",
     filename = "2026-isp-wind-traces.zip",
     status = :downloadable,
     local_path = "zip/Traces/2026-isp-wind-traces.zip",
     note = "Authoritative final 2026 ISP wind traces."),
]
