units = Dict(
                "Angaston"                          => [1, "Diesel", "Diesel", "Reciprocating Engine", -34.5035, 139.0245],
                "Barcaldine Power Station"          => [1, "Natural Gas", "OCGT", "OCGT", -23.55245, 145.314186],
                "Barker Inlet Power Station"        => [1, "Natural Gas", "OCGT", "OCGT", -34.804443, 138.525566],
                "Barron Gorge"                      => [2, "Hydro", "Run-of-River", "Vertical Francis", -16.85086, 145.6469],
                "Bastyan"                           => [1, "Hydro", "Reservoir", "Francis", -41.736, 145.5321],
                "Blowering"                         => [1, "Hydro", "Reservoir", "Francis", -35.39860, 148.246272],
                "Bogong / MacKay"                   => [12, "Hydro", "Reservoir", "Francis / Pelton", -36.8067, 147.2287],
                "Borumba"                           => [4, "Hydro", "Pumped-Storage", "Francis", -26.5394, 152.5542],
                "Braemar 2 Power Station"           => [3, "Natural Gas", "OCGT", "OCGT", -27.1109, 150.9053],
                "Callide C1"                        => [2, "Coal", "Coal", "Steam Super Critical", -24.3449, 150.6197],
                "Catagunya / Liapootah / Wayatinah" => [8, "Hydro", "Reservoir", "Francis", -42.4522, 146.5977],
                "Cethana"                           => [1, "Hydro", "Reservoir", "Francis", -41.481, 146.1338],
                "Dartmouth"                         => [8, "Hydro", "Reservoir", "Francis", -36.558, 147.5236],
                "Devils gate"                       => [1, "Hydro", "Reservoir", "Francis", -41.3505, 146.2633],
                "Dry Creek GT"                      => [3, "Natural Gas", "OCGT", "OCGT", -34.847463, 138.581758],
                "Eildon"                            => [2, "Hydro", "Reservoir", "Francis", -37.22186, 145.92137],
                "Fisher"                            => [1, "Hydro", "Reservoir", "Pelton", -41.6732, 146.2686],
                "Gordon"                            => [3, "Hydro", "Reservoir", "Francis", -42.7405, 145.9819],
                "Guthega"                           => [2, "Hydro", "Reservoir", "Francis", -36.35, 148.41353],
                "Hallett GT"                        => [12, "Natural Gas", "OCGT", "GE Frame 5", -33.3397, 138.732],
                "Hume Dam NSW"                      => [1, "Hydro", "Reservoir", "Kaplan", -36.1067, 147.0327],
                "Hume Dam VIC"                      => [1, "Hydro", "Reservoir", "Kaplan", -36.1067, 147.0327],
                "Hunter Valley GT"                  => [1, "Diesel", "Diesel", "Reciprocating Engine", -32.389253, 150.966396],
                "John Butters"                      => [1, "Hydro", "Reservoir", "Francis", -42.1548, 145.5344],
                "Kareeya"                           => [4, "Hydro", "Run-of-River", "Pelton", -17.76716, 145.5777],
                "Kidston "                          => [2, "Hydro", "Pumped-Storage", "Francis", -18.881970, 144.148635],
                "Kurri Kurri OCGT"                  => [2, "Natural Gas", "OCGT", "OCGT", -32.780599, 151.484749],
                "Lake Echo"                         => [1, "Hydro", "Reservoir", "Francis", -42.2536, 146.6206],
                "Lemonthyme / Wilmot"               => [2, "Hydro", "Reservoir", "Francis", -41.6038, 146.139],
                "Lonsdale"                          => [1, "Diesel", "Diesel", "Reciprocating Engine", -35.1097, 138.491],
                "Mackay GT"                         => [1, "Diesel", "Diesel", "Reciprocating Engine", -21.144566, 149.159097],
                "Mackintosh"                        => [1, "Hydro", "Reservoir", "Francis", -41.6994, 145.6472],
                "Meadowbank"                        => [1, "Hydro", "Reservoir", "Francis", -42.6111, 146.8457],
                "Mintaro GT"                        => [1, "Natural Gas", "OCGT", "OCGT", -33.9031, 138.7383],
                "Mount Piper"                       => [2, "Coal", "Black Coal", "Steam Sub Critical", -33.35889, 150.0313],
                "Mt Stuart"                         => [3, "Diesel", "Diesel", "Reciprocating Engine", -19.337998, 146.851171],
                "Murray 1"                            => [10, "Hydro", "Reservoir", "Francis", -36.2468, 148.1902],
                "Murray 2"                          => [4, "Hydro", "Reservoir", "Francis", -36.2425, 148.1364],
                "Oakey Power Station"               => [2, "Natural Gas", "OCGT", "OCGT", -27.418362, 151.679767],
                "Poatina"                           => [6, "Hydro", "Reservoir", "Nozzle-spear Pelton", -41.8115, 146.9192],
                "Port Lincoln GT"                   => [2, "Diesel", "Diesel", "Reciprocating Engine", -34.70019, 135.804728],
                "Port Stanvac 1"                    => [1, "Diesel", "Diesel", "Reciprocating Engine", -35.1104, 138.49146],
                "Reece"                             => [2, "Hydro", "Reservoir", "Francis", -41.7242, 145.1354],
                "Shoalhaven"                        => [4, "Hydro", "Pumped-Storage", "Reversible Francis", -34.7338, 150.46677],
                "Smithfield Energy Facility"        => [2, "Natural Gas", "OCGT", "OCGT", -33.85004, 150.949466],
                "Snowy 2.0"                         => [6, "Hydro", "Pumped-Storage", "Francis", -35.674518, 148.358518],
                "Snuggery"                          => [3, "Diesel", "Diesel", "Reciprocating Engine", -37.66455, 140.415558],
                "Somerton"                          => [3, "Natural Gas", "OCGT", "Frame 6B", -37.631822, 144.953077],
                "Snapper Point Power Station"       => [5, "Diesel", "Diesel", "Reciprocating Engine", -34.765, 138.5053],
                "Swanbank E GT"                     => [1, "Natural Gas", "CCGT", "CCGT", -27.660065, 152.814452],
                "Tamar Valley Combined Cycle"       => [1, "Natural Gas", "CCGT", "CCGT", -41.140125, 146.903636],
                "Tamar Valley Peaking"              => [1, "Natural Gas", "OCGT", "OCGT", -41.140125, 146.903636],
                "Tallawarra"                        => [2, "Natural Gas", "CCGT", "CCGT", -34.5228,	150.8081],
                "Tallawarra B"                      => [1, "Natural Gas", "OCGT", "OCGT", -34.5228, 150.8081],
                "Tarraleah"                         => [6, "Hydro", "Reservoir", "Pelton", -42.3012, 146.457],
                "Temporary Generation South"        => [4, "Diesel", "Diesel", "Reciprocating Engine", -35.1, 138.487],
                "Trevallyn"                         => [4, "Hydro", "Reservoir", "Francis", -41.4227, 147.1118],
                "Tribute"                           => [1, "Hydro", "Reservoir", "Francis", -41.8175, 145.6502],
                "Tumut 3"                           => [6, "Hydro", "Pumped-Storage", "Francis", -35.6112, 148.2917],
                "Tungatinah"                        => [5, "Hydro", "Reservoir", "Francis", -42.2967, 146.4565],
                "Upper Tumut"                       => [8, "Hydro", "Reservoir", "Francis", -35.94096, 148.3638],
                "Valley Power"                      => [6, "Natural Gas", "OCGT", "OCGT", -38.25362, 146.589166],
                "West Kiewa"                        => [4, "Hydro", "Reservoir", "Francis", -36.7601, 147.1861],
                "Wivenhoe"                          => [2, "Hydro", "Pumped-Storage", "Francis", -27.3722, 152.63194],
                "Yabulu PS"                         => [1, "Natural Gas", "CCGT", "CCGT", -19.201056, 146.618707],
                "Yabulu Steam Turbine "             => [1, "Natural Gas", "CCGT", "CCGT", -19.201056, 146.618707],
                "Yallourn W"                        => [4, "Coal", "Brown Coal", "Steam Sub Critical", -38.177015, 146.342783],
                "Yarwun 1"                          => [1, "Natural Gas", "CCGT", "CCGT", -23.830645, 151.15193]
            )

                
fueltype = Dict(    "Natural Gas"           => ["CCGT", "OCGT", "Gas-powered steam turbine", "Reciprocating Engine"],    
                    "Coal"                  => ["Steam Sub Critical", "Steam Super Critical"],
                    "Hydro"                 => ["Pumped Hydro", "Hydro"],
                    "Hydrogen"              => ["Hydrogen-based gas turbines"]
                )

#Map wind farm names to their corresponding generation profile file names
name_ex = Dict(     "Ararat Wind Farm"                          => "ARWF1_RefYear4006.csv", 
                    "Bango 973 Wind Farm"                       => "BANGOWF1_RefYear4006.csv", 
                    "Bango 999 Wind Farm"                       => "BANGOWF2_RefYear4006.csv", 
                    "Bald Hills Wind Farm"                      => "BALDHWF1_RefYear4006.csv", 
                    "Berrybank Wind Farm"                       => "BRYB1WF1_RefYear4006.csv",
                    "Boco Rock Wind Farm"                       => "BOCORWF1_RefYear4006.csv", 
                    "Bodangora Wind Farm"                       => "BODWF1_RefYear4006.csv", 
                    "Bulgana Green Power Hub - Wind Farm"       => "BULGANA1_RefYear4006.csv",
                    "Canunda Wind Farm"                         => "CNUNDAWF_RefYear4006.csv", 
                    "Capital Wind Farm"                         => "CAPTL_WF_RefYear4006.csv", 
                    "Cathedral Rocks Wind Farm"                 => "CATHROCK_RefYear4006.csv",
                    "Cattle Hill Wind Farm"                     => "CRURWF1_RefYear4006.csv", 
                    "Challicum Hills Wind Farm"                 => "CHALLHWF_RefYear4006.csv", 
                    "Cherry Tree Wind Farm"                     => "CHYTWF1_RefYear4006.csv",
                    "Clarke Creek Wind Farm"                    => "CLRKCWF1_RefYear4006.csv",  
                    "Clements Gap Wind Farm"                    => "CLEMGPWF_RefYear4006.csv", 
                    "Coopers Gap Wind Farm"                     => "COOPGWF1_RefYear4006.csv",
                    "Collector Wind Farm"                       => "COLWF01_RefYear4006.csv",
                    "Crookwell 2 Wind Farm"                     => "CROOKWF2_RefYear4006.csv",
                    "Crowlands Wind Farm"                       => "CROWLWF1_RefYear4006.csv",
                    "Crudine Ridge Wind Farm"                   => "CRURWF1_RefYear4006.csv",
                    "Cullerin Range Wind Farm"                  => "CULLRGWF_RefYear4006.csv", 
                    "Dundonnell Wind Farm"                      => "DUNDWF1_RefYear4006.csv",
                    "Dulacca Wind Farm"                         => "DULAWF1_RefYear4006.csv",
                    "Elaine Wind Farm"                          => "ELAINWF1_RefYear4006.csv",
                    "Granville Harbour Wind Farm"               => "GRANWF1_RefYear4006.csv", 
                    "Gullen Range Wind Farm"                    => "GULLRWF1_RefYear4006.csv", 
                    "Gullen Range Wind Farm 2"                  => "GULLRWF2_RefYear4006.csv", 
                    "Gunning Wind Farm"                         => "GUNNING1_RefYear4006.csv",
                    "Hallett 4 North Brown Hill Wind Farm"      => "NBHWF1_RefYear4006.csv", 
                    "Hallett 5 The Bluff Wind Farm"             => "BLUFF1_RefYear4006.csv", 
                    "Hallett Stage 1 Brown Hill Wind Farm"      => "HALLWF1_RefYear4006.csv",
                    "Hallett Stage 2 Hallett Hill Wind Farm"    => "HALLWF2_RefYear4006.csv", 
                    "Hornsdale Wind Farm Stage 1"               => "HDWF1_RefYear4006.csv", 
                    "Hornsdale Wind Farm Stage 2"               => "HDWF2_RefYear4006.csv",
                    "Hornsdale Wind Farm Stage 3"               => "HDWF3_RefYear4006.csv", 
                    "Kennedy Energy Park Wind Farm"             => "KABANWF1_RefYear4006.csv", 
                    "Kiata Wind Farm"                           => "KIATAWF1_RefYear4006.csv",
                    "Kaban Green Power Hub - Wind Farm"         => "KABANWF1_RefYear4006.csv",
                    "Lake Bonney 1 Wind Farm"                   => "LKBONNY1_RefYear4006.csv", 
                    "Lake Bonney 2 Wind Farm"                   => "LKBONNY2_RefYear4006.csv", 
                    "Lake Bonney 3 Wind Farm"                   => "LKBONNY3_RefYear4006.csv",
                    "Lal Lal Elaine Wind Farm"                  => "Lal_Lal_Elaine_RefYear4006.csv", 
                    "Lal Lal Yendon Wind Farm"                  => "Lal_Lal_Yendon_RefYear4006.csv", 
                    "Lincoln Gap Wind Farm - stage 1"           => "LGAPWF1_RefYear4006.csv",
                    "Lincoln Gap Wind Farm - stage 2"           => "LGAPWF2_RefYear4006.csv", 
                    "Macarthur Wind Farm"                       => "MACARTH1_RefYear4006.csv", 
                    "Moorabool Wind Farm"                       => "MOORAWF1_RefYear4006.csv",
                    "Mortlake South Wind Farm"                  => "MRTLSWF1_RefYear4006.csv", 
                    "Mortons Lane Wind Farm"                    => "MLWF1_RefYear4006.csv", 
                    "Mount Emerald Wind Farm"                   => "MEWF1_RefYear4006.csv",
                    "Mount Millar Wind Farm"                    => "MTMILLAR_RefYear4006.csv", 
                    "Mt Gellibrand Wind Farm"                   => "MTGELWF1_RefYear4006.csv", 
                    "Mt Mercer Wind Farm"                       => "MERCER01_RefYear4006.csv",
                    "Murra Warra Wind Farm - stage 1"           => "MUWAWF1_RefYear4006.csv", 
                    "Musselroe Wind Farm"                       => "MUSSELR1_RefYear4006.csv", 
                    "Oaklands Hill Wind Farm"                   => "OAKLAND1_RefYear4006.csv",
                    "Port Augusta Renewable Energy Park - Wind" => "S3_WH_Mid-North_SA_RefYear4006.csv",
                    "Portland Wind Farm"                        => "PORTWF_RefYear4006.csv", 
                    "Salt Creek Wind Farm"                      => "SALTCRK1_RefYear4006.csv", 
                    "Sapphire Wind Farm"                        => "SAPHWF1_RefYear4006.csv",
                    "Silverton Wind Farm"                       => "STWF1_RefYear4006.csv", 
                    "Snowtown S2 Wind Farm"             => "SNOWNTH1_RefYear4006.csv", 
                    # "Snowtown S2 Wind Farm - South"             => "SNOWSTH1_RefYear4006.csv",
                    "Snowtown Wind Farm"                        => "SNOWTWN1_RefYear4006.csv", 
                    "Starfish Hill Wind Farm"                   => "STARHLWF_RefYear4006.csv", 
                    "Stockyard Hill Wind Farm"                  => "STWF1_RefYear4006.csv",
                    "Taralga Wind Farm"                         => "TARALGA1_RefYear4006.csv", 
                    "Waterloo Wind Farm"                        => "WATERLWF_RefYear4006.csv", 
                    "Wattle Point Wind Farm"                    => "WPWF_RefYear4006.csv",
                    "Waubra Wind Farm"                          => "WAUBRAWF_RefYear4006.csv", 
                    "White Rock Wind Farm - Stage 1"            => "WRWF1_RefYear4006.csv", 
                    "Willogoleche Wind Farm"                    => "WGWF1_RefYear4006.csv",
                    "Woodlawn Wind Farm"                        => "WOODLWN1_RefYear4006.csv", 
                    "Woolnorth Wind Farm"                       => "WOOLNTH1_RefYear4006.csv", 
                    "Yaloak South Wind Farm"                    => "YSWF1_RefYear4006.csv",
                    "Yambuk Wind Farm"                          => "YAMBUKWF_RefYear4006.csv",
                    "Yendon Wind Farm" => "YENDWF1_RefYear4006.csv")

# Generate a function that returns name_ex parameterised based on the year, replacing 4006 with the desired year
function get_name_ex(year::Int)
    year_str = string(year)
    name_ex_year = Dict{String,String}()
    for (key, value) in name_ex
        new_value = replace(value, "4006" => year_str)
        name_ex_year[key] = new_value
    end
    return name_ex_year
end